
# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               sejinleecodes
tagline:             'and also blogs'
description:         'A blog where I share my honest thoughts, random ideas and unforgettable experiences'
url:                 http://lanyon.getpoole.com
baseurl:             '/sejinleecodes'
paginate:            5

# About/contact
author:
  name:              Se Jin Lee
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
