# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.


# Setup
title:               Sejinlee
tagline:             'blog'
description:         'A place where I'm going to post about my honest thoughts, random ideas, unforgettable memories and experiences'
url:                 http://lanyon.getpoole.com
baseurl:             '/sejinleecodes'
paginate:            5

# About/contact
author:
  name:              Se Jin Lee
  url:               https://www.facebook.com/sejin.lee.7370
  email:             sjleesogang@gmail.com

# Custom vars
version:             1.0.0
